#!/bin/sh

CV_FILE_NAME="marcel-cv"
TYPST_FILE_NAME="$CV_FILE_NAME.typ"

printf "Running pre-commit hook\n"
if ! [ -x "$(command -v typst)" ]; then
	echo 'Error: typst is not installed.' >&2
	exit 1
fi

COMPILE_OUTPUT=$(typst compile $TYPST_FILE_NAME 2>&1)

if echo "$COMPILE_OUTPUT" | grep -q "warning\|error"; then
	printf "Typst file compilation failed.\n"
	echo "--- OUTPUT ---"
	printf '%s\n' "$COMPILE_OUTPUT"
	exit 1
fi

echo "Typst file compilation successful"
git add "$CV_FILE_NAME.pdf"
exit 0
